FROM eclipse-temurin:21
RUN apt-get update && apt-get install -y netcat-openbsd

# create and swap to an unpriviledged user before launching into container for security reasons
RUN groupadd -r normal_user && useradd -r -g normal_user normal_user
RUN mkdir uploads/
RUN chown normal_user uploads/
USER normal_user

COPY app/build/libs/app.jar s4-backend-1.0.0.jar
ENTRYPOINT ["java","-jar","/s4-backend-1.0.0.jar"]