FROM bitnami/java:latest

# create and swap to an unpriviledged user before launching into container for security reasons
RUN groupadd -r normal_user && useradd -r -g normal_user normal_user
RUN mkdir uploads/
RUN chown normal_user uploads/

COPY entrypoint_app.sh /app/entrypoint_app.sh
RUN chmod +x /app/entrypoint_app.sh

USER normal_user
ENTRYPOINT ["/app/entrypoint_app.sh"]
