/*
 * This source file was generated by the Gradle 'init' task
 */
package s4.backend;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.ResponseBody;

import org.springframework.beans.factory.annotation.Autowired;

import org.springframework.http.ResponseEntity;

import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.SpringApplication;

import s4.backend.PhotoData;

@RestController
@SpringBootApplication
public class App {
    @Autowired 
    private PhotoDataRepository photoDataRepo; 

   	@RequestMapping("/")
    public String getGreeting() {
        return "Hello New World!";
    }

    @PostMapping("/add")
    public String add(){
        PhotoData i = new PhotoData();
        i.setName("test");

        photoDataRepo.save(i);
        return "test image added";
    }

    @RequestMapping("/query")
    public @ResponseBody Iterable<PhotoData> query() {
       return photoDataRepo.findAll();
    }


    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
