/*
 * This source file was generated by the Gradle 'init' task
*/
package s4.backend;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

import org.junit.jupiter.api.BeforeAll;

class AppTest {
     
    @BeforeAll
    static void checkProfile() {
        assumeTrue(
            "test".equals(System.getProperty("spring.profiles.active")),
            "Skipping entire class because profile is not test"
        );
    }
    
    @DisplayName("Should show a basic API greeting")
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    public void testJwtDecoder() {
        // This will show you the actual exception
    }

} 
