/*
 * This source file was generated by the Gradle 'init' task
*/
package s4.backend;

import com.github.dockerjava.api.DockerClient;
import com.github.dockerjava.core.DockerClientBuilder;
import com.github.dockerjava.api.exception.DockerException;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

import org.junit.jupiter.api.BeforeAll;


class DockerTest {
    
    @BeforeAll
    static void checkProfile() {
        assumeTrue(
            "test".equals(System.getProperty("spring.profiles.active")),
            "Skipping entire class because profile is not test"
            
        );
    }
    
    @Test
    @DisplayName("Should successfully connect to Docker daemon")
    public void testDockerConnection() {
        // this test fails on Windows because Docker is working a different way
        if(System.getProperty("os.name").startsWith("Linux"))
        {
            assertDoesNotThrow(() -> {
                DockerClient dockerClient = DockerClientBuilder.getInstance().build();
                assertNotNull(dockerClient, "Docker client should not be null");
            });
        }
    }
    
    @Test
    @DisplayName("Should run Postgres Docker image successfully")
    public void testPostgresContainer() throws InterruptedException {
        String container = "bitnami/postgresql:latest";

        // this test fails on Windows because Docker is working a different way
        if(System.getProperty("os.name").startsWith("Linux"))
        {
            assertDoesNotThrow(() -> {
                DockerClient dockerClient = DockerClientBuilder.getInstance().build();
                
                // Pull the hello-world image
                dockerClient.pullImageCmd(container).exec(new com.github.dockerjava.core.command.PullImageResultCallback()).awaitCompletion();
                
                // Create and run the container
                String containerId = dockerClient.createContainerCmd(container).exec().getId();
                assertNotNull(containerId, "Container ID should not be null");
                
                // Start the container
                dockerClient.startContainerCmd(containerId).exec();
                
                dockerClient.stopContainerCmd(containerId).withTimeout(10).exec();
                
                // Clean up - remove the container
                dockerClient.removeContainerCmd(containerId).exec();

                dockerClient.close();
            });
        }
    }

} 
